# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Physolism
email: physolism@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Foodie & Photography
logo: "/assets/images/me.jpg"
home: "/assets/images/home.png"
cover: "/assets/images/DSC_0465-2.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
#url: http://localhost:4000 # the base hostname & protocol for your site
url: http://physolism.github.io
twitter_username: physolism
github_username:  physolism
twitter_handle: '@physolism'


name: 'Physolism'
author: 'Peace Rittha'
author_image: "/assets/images/me.jpg"

paginate: 5

social:
  - icon:	twitter
    url:	https://twitter.com/physolism
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/physolism
    desc: Connect with my facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/physolism
    desc:	Fork me on github


# Build settings
future: true
markdown: kramdown
exclude: [Rakefile]
gems: [jekyll-coffeescript, jekyll-watch, jekyll-assets, jemoji, jekyll-paginate]
